openapi: '3.0.2'
info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture Training
    email: joe@doe.com
    url: github.com
servers:
  - url: http://localhost:8080
paths:
  /customer:
    post:
      description: Create Customer
      summary: Create Customer for given request
      operationId: createCustomer
      requestBody:
        description: Create customer schema
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        '500':
          description: Internal Server Error
  /customer/{id}:
    get:
      operationId: getCustomer
      description: Fetch customer details
      parameters:
        - name: id
          in: path
          required: true
          description: fetch customer
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal Server Error

components:
  schemas:
    Customer:
      description: This is the customer model
      type: object
      required:
        - "customerId"
      properties:
        customerId:
          type: string
          description: Id of the customer
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          description: Name of the customer  (first  and last name)
          example: Joe Doe
        customerAddress:
          type: string
          example: 1000 Main Street, Hartford
